/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Man(props) {
  const man = useRef();
  const { nodes, materials, animations } = useGLTF("./man.glb");
  const { actions } = useAnimations(animations, man);

  useEffect(() => {
    actions["Typing"].play()
  }, [])
  return (
    <group ref={man} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Lewis"
          position={[0.026, -0.491, 0.131]}
          rotation={[1.404, 0.023, 0.007]}
        >
          <skinnedMesh
            name="Lewis_Hair_B"
            geometry={nodes.Lewis_Hair_B.geometry}
            material={materials.Lewis_Mat}
            skeleton={nodes.Lewis_Hair_B.skeleton}
          />
          <skinnedMesh
            name="Lewis_Head_B"
            geometry={nodes.Lewis_Head_B.geometry}
            material={materials.Lewis_Mat}
            skeleton={nodes.Lewis_Head_B.skeleton}
            morphTargetDictionary={nodes.Lewis_Head_B.morphTargetDictionary}
            morphTargetInfluences={nodes.Lewis_Head_B.morphTargetInfluences}
          />
          <skinnedMesh
            name="Lewis_Pants_A"
            geometry={nodes.Lewis_Pants_A.geometry}
            material={materials.Lewis_Mat}
            skeleton={nodes.Lewis_Pants_A.skeleton}
          />
          <skinnedMesh
            name="Lewis_Shirt_A"
            geometry={nodes.Lewis_Shirt_A.geometry}
            material={materials.Lewis_Mat}
            skeleton={nodes.Lewis_Shirt_A.skeleton}
          />
          <skinnedMesh
            name="Lewis_Shoes_B"
            geometry={nodes.Lewis_Shoes_B.geometry}
            material={materials.Lewis_Mat}
            skeleton={nodes.Lewis_Shoes_B.skeleton}
          />
          <primitive object={nodes.hips} />
        </group>
        {/*<mesh*/}
        {/*  name="Table"*/}
        {/*  castShadow*/}
        {/*  receiveShadow*/}
        {/*  geometry={nodes.Table.geometry}*/}
        {/*  material={nodes.Table.material}*/}
        {/*  position={[0, 0.721, 0.868]}*/}
        {/*  scale={[1, 0.021, 0.443]}*/}
        {/*/>*/}
        {/*<mesh*/}
        {/*  name="Keyboard"*/}
        {/*  castShadow*/}
        {/*  receiveShadow*/}
        {/*  geometry={nodes.Keyboard.geometry}*/}
        {/*  material={nodes.Keyboard.material}*/}
        {/*  position={[0.09, 0.754, 0.608]}*/}
        {/*  scale={[0.271, 0.008, 0.067]}*/}
        {/*/>*/}
      </group>
    </group>
  );
}

useGLTF.preload("/man.glb");
