export * from './header/Header'
export * from './hero-section/HeroSection'
export * from './bio-section/BioSection'
export * from './work-section/WorkSection'
export * from './contact-section/ContactSection'