/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Chair(props) {
  const { nodes, materials } = useGLTF("/chair.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.003, -0.049, 0.085]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.851}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Wheels_geo_Chair_Part_0.geometry}
          material={materials.Chair_Part}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Wheels_geo_Seat_0.geometry}
          material={materials.Seat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Wheels_geo_Wheel_0.geometry}
          material={materials.Wheel}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/chair.glb");
